name: SPA Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 14.x
    steps:
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: node_modules
          key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install -g yarn
      - run: yarn build
      - run: mv build/index.html build/404.html
